title: Vatsal Sanjay
description: Personal Website
baseurl: "/VatsalSy"
url: "https://comphy-lab.org"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Site settings
permalink: /:title/

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:name 